### ISSUE TITLE
Randomly failing test case in Create spec

### ISSUE THREAD

**Issue by 0x4d** [renew-js/renew-lib#75] opened 2019-04-02 14:02 UTC
## Describe the bug
Test case `modules/create - Create Tool should have a position` fails randomly when running tests in rapid succession.
```
Firefox 66.0.0 (Linux 0.0.0) modules/create - Create Tool should have a position FAILED
	NS_ERROR_FAILURE:  thrown
Firefox 66.0.0 (Linux 0.0.0): Executed 89 of 106 (1 FAILED) (0 secs / 0.368 secs)
Firefox 66.0.0 (Linux 0.0.0) modules/create - Create Tool should have a position FAILED
```

## To Reproduce
1. `npm run dev`
2. Save a spec file to cause tests to run
3. Wait until tests are through
4. a. Aforementioned error appears
    b. Everything is fine GOTO step 2

## Expected behavior
Test are deterministic.

## Additional context
Calling `toolbox.activate('create');` directly after `document.dispatchEvent(...)` probably results in a race condition.

**Comment by tim-kilian** [comment] 2019-04-02 20:49
Did you got this on travis or did it happen locally ? Maybe it's related to your environment, because I didn't noticed a failure. However I will check this test case.

**Comment by tim-kilian** [comment] 2019-04-02 22:36
Remember that the second parameter object in [MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent)(typeArg, mouseEventInit) should be unique. Clone it before passing it.

**Comment by 0x4d** [comment] 2019-04-02 22:41
Yes only locally. I'm sticking with my suspicion of a race condition. As travis also uses Firefox and Linux it might very well be related to processing speed.

**Comment by tim-kilian** [comment] 2019-04-02 23:05
Seems to be able to reproduce on all environments and still fails randomly.

**Comment by tim-kilian** [comment] 2019-04-15 21:01
I removed the test case and close this issue.

**Closed as completed by tim-kilian** 2019-04-15 21:01 UTC
Labels: bug
